# Generated by Django 4.0.5 on 2022-07-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('titulo', models.CharField(max_length=40)),
                ('subtitulo', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField()),
                ('cuerpo', models.CharField(max_length=900)),
            ],
        ),
    ]
